import Head from "next/head";
export const title = "HelloWorld";
export const title2 = "Este es otro div";

const Home = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="bg-blue-300">{title}</div>
        <div>{title2}</div>
      </main>
    </>
  );
};

export default Home;
